// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:untitled/models/auth/auth_model.dart';
import 'package:untitled/models/transaction_product_inbound/transaction_product_inbound_model.dart';
import 'package:untitled/models/transaction_product_outbound/transaction_product_outbound_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthModelAdapter());
    registerAdapter(TransactionProductInboundModelAdapter());
    registerAdapter(TransactionProductOutboundModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthModelAdapter());
    registerAdapter(TransactionProductInboundModelAdapter());
    registerAdapter(TransactionProductOutboundModelAdapter());
  }
}
